install.packages('rworldmap',dependencies=TRUE) 
library(rworldmap)
install.packages("xlsx")
library("xlsx")
install.packages("readxl")
library(readxl)
data<-read_excel("C:\\Users\\Melis Y\\Desktop\\ders\\applied stat\\countries_excel.xlsx")
data
colnames(data)
help("joinCountryData2Map")
sPDF<- joinCountryData2Map(data, joinCode = "ISO2", nameJoinColumn = "CCode", nameCountryColumn = "country", suggestForFailedCodes = FALSE, mapResolution = "coarse", projection = NA, verbose = FALSE)
par(mai=c(0.2,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData( sPDF,nameColumnToPlot="I1deneme")
mapParams <- mapCountryData( sPDF, nameColumnToPlot="I1deneme", addLegend=FALSE )
do.call( addMapLegend, c(mapParams, legendWidth=0.5, legendMar = 2))
help("mapCountryData")
