library(tidyr)
library(ggcorrplot)
library(ggpubr)
library(dplyr)


setwd("D:\\DigiserData\\deno")
getwd()
X <- read.csv("indices.csv", head=T, sep = ";")
X <- X[,-1]


#Create lvl4 which include all data at last layers:
lvl4 <- X%>%
  select(names(X)[nchar(names(X))>7 & nchar(names(X))<9],names(X)[nchar(names(X))>5 & nchar(names(X))<7],-I2_2_1, -I2_2_2, -I2_2_3, -I2_2_4 )

names(lvl4)

#Correlations:
corr4 <- round(cor(lvl4),1)
x11()
ggcorrplot(corr3)


# Boxplot
x11()
par(mar=rep(8,4))
boxplot(scale(x=lvl4, center=T, scale=F), col='gold')
#Variability in L1_2_2 and L2_2_1_1 higher than the others


#PCA test on level 4 
pc_4 <- princomp(lvl4)
summary(pc_4)
pc_4


# Explained variance
x11()
layout(matrix(c(2,3,1,3),2,byrow=T))
plot(pc_4, las=2, main='Principal components')
barplot(sapply(lvl4,sd)^2, las=2, main='Original Variables', ylab='Variances')
plot(cumsum(pc_4$sd^2)/sum(pc_4$sd^2), type='b', axes=F, xlab='number of components', 
     ylab='contribution to the total variance')
abline(h=1, col='blue')
abline(h=0.83, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(lvl4),labels=1:ncol(lvl4),las=2)
# The first 8 PC explains 83% of the total variability. 
#cumsum(pc_4$sd^2)/sum(pc_4$sd^2)

#Scores
scores.lvl4 <- pc_4$scores
scores.lvl4

# Projection on the space generated by the k-th principal component
x11(width=21, height=7)
par(mfrow=c(3,6))
matplot(t(lvl4), type='l', main = 'Data', ylim=range(lvl4))
mean4 <- colMeans(lvl4)
matplot(mean4, type='l', main = 'First 0 PCs', lwd=2, ylim=range(lvl4))
projection <- matrix(mean4, dim(lvl4)[[1]], dim(lvl4)[[2]], byrow=T)
for(i in 1:15)
{
  projection <- projection + scores.lvl4[,i] %*% t(load.pc4[,i])
  matplot(t(projection), type='l', main = paste('First', i, 'PCs'), ylim=range(lvl4))
  matplot(mean4, type='l', lwd=2, add=T)
}

#### We should take first 8 PC to explain data best 





#loadings (recall: coefficients of the linear combination of the original 
#           variables that defines each principal component)
load.pc4 <- pc_4$loadings
load.pc4 

row.names(load.pc4)
length(load.pc4)

# graphical representation: loadings of first 8 PC that explain %83 of data:
x11()
par(mfcol = c(2,4))
for(i in 1:7) barplot(load.pc4[,i], ylim = c(-1, 1), main=paste("PC",i))

# Interpretation of the loadings:
##First PCs: direct proportion to all
##Other 7 PC tells us the 9 of them are important(very negative or positive) variables which are:
### I1_1_1, I1_1_3, I1_2_1, 
#   I_1_2_2, I2_2_1_1, I2_2_3_3, 
#   I_2_2_4_3, I2_2_3_2, I2_2_1_5


#box plot with PCs
x11()
layout(matrix(c(1,2),2))
boxplot(lvl4, las=2, col='gold', main='Original variables')
scores.lvl4 <- data.frame(scores.lvl4)
boxplot(scores.lvl4, las=2, col='gold', main='Principal components')

# x11()
# biplot(pc_4)
# help(biplot)
#################################






